# Generated by Django 4.1.5 on 2023-03-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transid', models.PositiveIntegerField()),
                ('transdate', models.DateField()),
                ('gender', models.CharField(max_length=70)),
                ('age', models.IntegerField(default=0)),
                ('maritalstatus', models.CharField(max_length=70)),
                ('statenames', models.CharField(max_length=70)),
                ('segment', models.CharField(max_length=70)),
                ('employeestatus', models.CharField(max_length=70)),
                ('paymentmode', models.CharField(max_length=70)),
                ('referal', models.IntegerField(default=0)),
                ('amountspent', models.FloatField(default=0.0)),
            ],
        ),
    ]
